# -*- coding: utf-8 -*-
"""lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rPUtFwg6QhRDAjEXVM9VUqCAQwIn0Zqx
"""

x = 1

y = 2

x + y

