# -*- coding: utf-8 -*-
"""python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pOLUJSMs6fhtMFU6eyjtpZ0wXpMGGZdl
"""

print("Hello world")

